services:
  python-red-file:
    build: .
    container_name: python-red-file
    ports:
      - ${PYTHON_EXTERNAL_PORT}:${PYTHON_INTERNAL_PORT}
    networks:
      - network_red_file
    volumes:
      - .:/app/

  minio-red-file:
    image: quay.io/minio/minio
    container_name: minio-red-file
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      BRONZE_BUCKET: ${BRONZE_BUCKET}
      SILVER_BUCKET: ${SILVER_BUCKET}
      GOLD_BUCKET: ${GOLD_BUCKET}
    ports:
      - ${MINIO_API_PORT_EXTERNAL}:${MINIO_API_PORT_INTERNAL}
      - ${MINIO_CONSOLE_PORT_EXTERNAL}:${MINIO_CONSOLE_PORT_INTERNAL}
    command: server /data --console-address ":${MINIO_CONSOLE_PORT_INTERNAL}"
    networks:
      - network_red_file
    volumes:
      - volume-minio-red-file:/data

  postgres-red-file:
    image: postgres
    container_name: postgres-red-file
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    restart: always
    volumes:
      - volume-postgre-red-file:/var/lib/postgresql
    ports:
      - ${POSTGRES_EXTERNAL_PORT}:${POSTGRES_INTERNAL_PORT}
    networks:
      - network_red_file

  pgadmin-red-file:
    image: dpage/pgadmin4
    container_name: pgadmin-red-file
    depends_on:
      - postgres-red-file
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_EXTERNAL_PORT}:${PGADMIN_INTERNAL_PORT}
    volumes:
      - volume-pgadmin-red-file:/var/lib/pgadmin
    networks:
      - network_red_file

networks:
  network_red_file:

volumes:
  volume-minio-red-file:
  tp-volume-ex4:
  volume-postgre-red-file:
  volume-pgadmin-red-file: